"""expense source key

Revision ID: 34ada1d93b4b
Revises: cdf791184e60
Create Date: 2026-09-21 08:45:54.061467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '34ada1d93b4b'
down_revision: Union[str, Sequence[str], None] = 'cdf791184e60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('source_key', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True))
    op.create_index(op.f('ix_expenses_source_key'), 'expenses', ['source_key'], unique=False)
    op.create_unique_constraint('uq_expenses_user_source', 'expenses', ['user_id', 'source_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_expenses_user_source', 'expenses', type_='unique')
    op.drop_index(op.f('ix_expenses_source_key'), table_name='expenses')
    op.drop_column('expenses', 'source_key')
    # ### end Alembic commands ###
